# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joey A. Miller Foundation
description: > # this means to ignore newlines until "baseurl:"
    Joey A. Miller Foundation
# Changed baseurl to /stage for testing. -- Nick
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://joeyamillerfoundation.org" # the base hostname & protocol for your site

#twitter_username: 
github_username:  camdenmil

#Global Conf
exclude: ['*.sh'] #Don't put scripts in the destination directory
timezone: 'America/New_York'
encoding: 'utf-8'


# Build
markdown: kramdown
plugins: [jekyll-paginate]
excerpt_separator: ""
